import os
import json
import requests
import logging
from pathlib import Path
from dotenv import load_dotenv

# Config
LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
logging.basicConfig(level=logging.INFO, format=LOG_FORMAT)
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()

NOTION_TOKEN = os.getenv("NOTION_API_KEY")
DATABASE_ID = os.getenv("NOTION_DATABASE_ID")
ONEDRIVE_INBOX = os.getenv("ONEDRIVE_INBOX_PATH", "OneDrive_Inbox")

headers = {
    "Authorization": f"Bearer {NOTION_TOKEN}",
    "Content-Type": "application/json",
    "Notion-Version": "2022-06-28",
}

def get_ready_keywords():
    url = f"https://api.notion.com/v1/databases/{DATABASE_ID}/query"
    payload = {
        "filter": {
            "property": "Status",
            "select": {
                "equals": "Ready for n8n"
            }
        }
    }
    response = requests.post(url, headers=headers, json=payload)
    if response.status_code == 200:
        return response.json().get("results", [])
    else:
        logger.error(f"Error querying Notion: {response.status_code} - {response.text}")
        return []

def update_notion_status(page_id, status_name):
    url = f"https://api.notion.com/v1/pages/{page_id}"
    payload = {
        "properties": {
            "Status": {
                "select": {
                    "name": status_name
                }
            }
        }
    }
    response = requests.patch(url, headers=headers, json=payload)
    return response.status_code == 200

def generate_markdown(item, output_dir: Path):
    props = item["properties"]
    
    # Helper to get rich text content
    def get_text(prop_name):
        text_list = props.get(prop_name, {}).get("rich_text", [])
        return text_list[0]["text"]["content"] if text_list else ""

    # Helper to get title content
    def get_title():
        title_list = props.get("Nombre", {}).get("title", [])
        return title_list[0]["text"]["content"] if title_list else "Untitled"

    keyword = get_text("Focus Keyword")
    slug = get_text("Slug") or keyword.replace(" ", "-").lower()
    title_a = get_title()
    title_b = get_text("Title B")
    title_c = get_text("Title C")
    hero_prompt = get_text("Hero Prompt")
    twist_a_prompt = get_text("Twist A Prompt")
    twist_b_prompt = get_text("Twist B Prompt")
    
    # Payload Construction (Aligning with README_WORKFLOW_ONEDRIVE_WP.md v4)
    content = f"""---
title: "{title_a}"
seo_title: "{title_a} | JobNearMe"
meta_description: "Find the best {keyword} opportunities in 2026. Explore salaries, requirements, and top companies hiring now."
focus_keyword: "{keyword}"
canonical_url: "https://jobnearme.online/{slug}/"
excerpt: "Discover the latest trends and opportunities in {keyword} for 2026. Your career freedom starts here."
status: "draft"
category_ids: "2"
tag_ids: "1,2"
project: "jobnearme"
image_path: "images/{slug}.png"
visual_triad:
  hero: {{ prompt: "{hero_prompt}", purpose: "WP Featured / FB Post" }}
  twist_a: {{ prompt: "{twist_a_prompt}", purpose: "Short A / Scene 1" }}
  twist_b: {{ prompt: "{twist_b_prompt}", purpose: "Short B / Scene 2" }}
---

# {title_a}

## The Paradigm Shift
**{keyword.title()}** is no longer just an "option" or a corporate benefit. It is the foundation of the new digital economy. If you are still trapped in a 9-to-5 office, you are missing out on the greatest transfer of freedom in history. In this 2026, authority is built on results, not on "chair-hours."

## Why {keyword.title()} is the Holy Grail
1. **Geographic Arbitrage**: You earn in strong currencies and spend in your local currency. It's pure mathematics applied to freedom.
2. **Extreme Productivity**: No office interruptions, no useless commutes that steal your life. Your time is yours again.
3. **Scalability**: The Trafficker model allows you to manage multiple projects or clients from your digital bunker without a glass ceiling.

## Success Structure in {keyword.title()}
To dominate this market, you need three fundamental pillars:
- **Skills Audit**: Don't try to do everything. Specialize in what the digital market really demands today.
- **Elite Infrastructure**: Your office is your temple. If your work tool fails, your business fails.
- **Trafficker Mindset**: Iron discipline and focus on ROI. We are not here to "try," we are here to dominate.

## Conclusion: Freedom is Not Requested, It's Built
Don't wait for someone to give you permission to be free. **{keyword.title()}** is the first brick of your new life. Get moving, start today, and don't look back.

---
*This post was generated by the Funnels Foundry Content Factory - Authority in Career and Digital Freedom.*
"""
    
    outfile = output_dir / f"{slug}.md"
    with open(outfile, 'w', encoding='utf-8') as f:
        f.write(content)
    return outfile

def main():
    # Resolve paths
    base_dir = Path(__file__).resolve().parent.parent
    out_dir = base_dir / ONEDRIVE_INBOX
    
    if not out_dir.exists():
        logger.error(f"Output directory not found: {out_dir}")
        return

    logger.info("Querying Notion for 'Ready for n8n' items...")
    items = get_ready_keywords()
    
    if not items:
        logger.info("No items found with status 'Ready for n8n'.")
        return

    logger.info(f"Found {len(items)} items to process.")
    
    for item in items:
        page_id = item["id"]
        keyword = item["properties"].get("Focus Keyword", {}).get("rich_text", [{}])[0].get("text", {}).get("content", "Unknown")
        
        try:
            outfile = generate_markdown(item, out_dir)
            logger.info(f"Generated payload: {outfile.name} for keyword: {keyword}")
            
            # Update Notion status
            if update_notion_status(page_id, "🚀 Publish: WordPress"):
                logger.info(f"Updated Notion status to '🚀 Publish: WordPress' for {keyword}")
            else:
                logger.warning(f"Failed to update Notion status for {keyword}")
                
        except Exception as e:
            logger.error(f"Error processing item {page_id} ({keyword}): {e}")

if __name__ == "__main__":
    main()
